name: Build Shopware Image

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  versions:
    name: Determine Shopware versions to build
    runs-on: ubuntu-24.04
    outputs:
      first-version: ${{ steps.versions.outputs.first-version }}
      latest-version: ${{ steps.versions.outputs.latest-version }}
      lts-first-version: ${{ steps.versions.outputs.lts-first-version }}
      lts-latest-version: ${{ steps.versions.outputs.lts-latest-version }}
    steps:
      - name: Generate versions
        id: versions
        uses: shopware/github-actions/versions@main

  build-test-image:
    runs-on: ubuntu-24.04
    needs: [ versions ]
    permissions:
      packages: write
    strategy:
      matrix:
        include:
          - PHP_VERSION: 8.3
            SHOPWARE_VERSION: ${{ needs.versions.outputs.first-version }}
            SHOPWARE_BUILD_SOURCE: tag
          - PHP_VERSION: 8.3
            SHOPWARE_VERSION: ${{ needs.versions.outputs.latest-version }}
            SHOPWARE_BUILD_SOURCE: tag
          - PHP_VERSION: 8.3
            SHOPWARE_VERSION: ${{ needs.versions.outputs.lts-first-version }}
            SHOPWARE_BUILD_SOURCE: tag
          - PHP_VERSION: 8.3
            SHOPWARE_VERSION: ${{ needs.versions.outputs.lts-latest-version }}
            SHOPWARE_BUILD_SOURCE: tag
          - PHP_VERSION: 8.3
            SHOPWARE_VERSION: 6.6.x
            SHOPWARE_BUILD_SOURCE: branch
          - PHP_VERSION: 8.4
            SHOPWARE_VERSION: trunk
            SHOPWARE_BUILD_SOURCE: branch
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
          sparse-checkout: |-
            test-image.Dockerfile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login into Github Docker Registery
        if: ${{ !env.ACT }}
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ env.ACT && 'false' || 'true' }}
          tags: ghcr.io/${{ github.repository }}/test-image:${{ matrix.SHOPWARE_VERSION }}
          file: test-image.Dockerfile
          build-args: |
            PHP_VERSION=${{ matrix.PHP_VERSION }}
            SHOPWARE_VERSION=${{ matrix.SHOPWARE_VERSION }}
            SHOPWARE_BUILD_SOURCE=${{ matrix.SHOPWARE_BUILD_SOURCE }}
