on:
    push:
        branches:
            - trunk
name: release-please

permissions:
    id-token: write

jobs:
    release-please:
        runs-on: ubuntu-latest
        steps:
            - uses: octo-sts/action@v1.1.1
              id: sts-release
              with:
                  scope: shopware/acceptance-test-suite
                  identity: release
            - uses: googleapis/release-please-action@v5
              id: release
              with:
                  release-type: node
                  token: ${{ steps.sts-release.outputs.token }}
            # The logic below handles the npm publication:
            - uses: actions/checkout@v7
              # these if statements ensure that a publication only occurs when
              # a new release is created:
              if: ${{ steps.release.outputs.release_created }}
            - uses: actions/setup-node@v6
              with:
                  node-version: "lts/*"
                  cache: "npm"
              if: ${{ steps.release.outputs.release_created }}
            - run: npm ci
              if: ${{ steps.release.outputs.release_created }}
            # authentication happens automatically via OIDC. See https://www.npmjs.com/package/@shopware-ag/acceptance-test-suite/access for more details.
            - run: npm publish
              if: ${{ steps.release.outputs.release_created }}
