on:
    pull_request:
    workflow_dispatch:

name: test
jobs:
    eslint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: 20
            registry-url: "https://registry.npmjs.org"
        - run: npm ci
        - run: npm run lint
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: 20
            registry-url: "https://registry.npmjs.org"
        - run: npm ci
        - run: npm run build
    test:
      name: test shopware ${{ matrix.SHOPWARE_VERSION }}
      timeout-minutes: 15
      runs-on: ubuntu-latest
      strategy:
        matrix:
          include:
            - PHP_VERSION: 8.3
              SHOPWARE_VERSION: latest
              SHOPWARE_BUILD_SOURCE: tag
              PORT: 8031
            - PHP_VERSION: 8.3
              SHOPWARE_VERSION: 6.6.x
              SHOPWARE_BUILD_SOURCE: branch
              PORT: 8021
            - PHP_VERSION: 8.4
              SHOPWARE_VERSION: trunk
              SHOPWARE_BUILD_SOURCE: branch
              PORT: 8011
      env:
        WEBSERVER_COMMAND: '' # this will disable the log output
        PHP_VERSION: ${{ matrix.PHP_VERSION }}
        SHOPWARE_VERSION: ${{ matrix.SHOPWARE_VERSION }}
        SHOPWARE_BUILD_SOURCE: ${{ matrix.SHOPWARE_BUILD_SOURCE }}
        PORT: ${{ matrix.PORT }}
      steps:
      - uses: actions/checkout@v4

      - name: Start shopware
        run: docker compose up --pull=always --quiet-pull --wait

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        env:
          APP_URL: http://localhost:${{ matrix.PORT }}
        run: npx playwright test --repeat-each 4

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.SHOPWARE_VERSION }}
          path: test-results/
          retention-days: 7

    test-saas:
      timeout-minutes: 15
      runs-on: ubuntu-latest
      concurrency: saas # only allow one job at a time
      env:
        APP_URL: ${{ secrets.SAAS_APP_URL }}
        SHOPWARE_ADMIN_USERNAME: ${{ secrets.SAAS_SHOPWARE_ADMIN_USERNAME }}
        SHOPWARE_ADMIN_PASSWORD: ${{ secrets.SAAS_SHOPWARE_ADMIN_PASSWORD }}
      steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test --repeat-each 2
